// <auto-generated />
namespace MindFork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student));
        
        string IMigrationMetadata.Id
        {
            get { return "201812141656399_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
